### ISSUE TITLE
UI Dropdown text is broken on Windows 10

### ISSUE THREAD

**Issue by Vincent-P** [mantrajs/mantrajs-atom-package#18]
I'm on Windows 10 and the dropdown text is cut off.

![mantra_issue](https://cloud.githubusercontent.com/assets/10779205/13425767/52ec31a6-dfa9-11e5-8292-35fb8f4b9e43.PNG)

Adding this line fix this : 

``` less
.mantra.atom-pane select {
  padding: 0 12px 0 12px;
}
```
